---
driver:
  name: vagrant

driver_config:
  customize:
    cpus: 4
    memory: 4096
  require_chef_omnibus: true
  network:
    - [ 'private_network', { ip: '192.168.33.80' }]
    - [ 'forwarded_port', { guest: 80, host: 8480, auto_correct: true } ]
    - [ 'forwarded_port', { guest: 443, host: 8443, auto_correct: true } ]
    - [ 'forwarded_port', { guest: 8080, host: 8080, auto_correct: true } ]

provisioner:
  name: chef_zero
  environments_path: "environments"
  nodes_path: "nodes"
  data_bags_path: "data_bags"
  encrypted_data_bag_secret_key_path: "test/data/secret.txt"
  client_rb:
    environment: test
    diff_disable: true
  attributes:
    networked_services:
      http:
        ports: [80, 8080]
        ips: [0.0.0.0/0]
        protocols: [tcp]
      https:
        ports: [443]
        ips: [0.0.0.0/0]
        protocols: [tcp]
      ssh:
        ports: [22]
        ips: [0.0.0.0/0]
        protocols: [tcp]

platforms:
- name: centos-6.6
  driver:
    box: bento/centos-6.6
  driver_config:
    require_chef_omnibus: "12.11.18"
- name: ubuntu-14.04
  driver:
    box: bento/ubuntu-14.04
  driver_config:
    require_chef_omnibus: "12.11.18"

suites:
  - name: jenkins
    excludes:
      centos-6.6
    run_list:
      - recipe[jenkins_ci::virtualbox]
      - recipe[jenkins_ci::vagrant]
      - recipe[jenkins_ci::apache]
      - recipe[jenkins_ci::rbenv]
      - recipe[jenkins::java]
      - recipe[jenkins_ci::default]
