name             'jenkins_ci'
maintainer       'Brian E Clow'
maintainer_email 'bclow-github@temporalflux.org'
license          'Apache 2.0'
description      'Cookbook to ease the use of Jenkins for Chef Cookbook CI'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.5.0'

depends 'apache2', '~> 3.0.1'
depends 'apt'
depends 'docker', '~> 0.37.0'
depends 'git', '~> 4.1.0'
depends 'java'
depends 'jenkins', '~> 2.4.1'
depends 'rbenv', '~> 1.7'
depends 'runit', '= 1.6.0'
depends 'sysctl', '~> 0.6.2'
depends 'users', '~> 1.8.2'
depends 'vagrant', '= 0.2.2'
depends 'virtualbox', '= 1.0.0'
depends 'yum'
